# Generated by Django 4.1.4 on 2022-12-28 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new_feature", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Images",
            new_name="GestationalImages",
        ),
        migrations.AlterModelTable(
            name="gestationalimages",
            table="gestation_images",
        ),
    ]
