# Generated by Django 4.1.4 on 2022-12-28 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("new_feature", "0002_rename_images_gestationalimages_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gestationaltable",
            name="images",
        ),
        migrations.AddField(
            model_name="gestationalimages",
            name="gestation",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gestation",
                to="new_feature.gestationaltable",
            ),
            preserve_default=False,
        ),
    ]
